import { useState } from "react";
import { ExternalLink, FileCheck2, Pencil } from "lucide-react";
import type { TravelDocument } from "../types";
import { documentSummary, readinessItems } from "../utils/documents";
import { Modal } from "./Modal";

const statuses: TravelDocument["status"][]=["Pendiente","En trámite","Aprobado","Completado","No aplica","Vencido"];
export function DocumentsScreen({ documents, hotels, reservations, onSave, mode="documents" }: { documents: TravelDocument[]; hotels: Array<{id:string;name:string;status:string;archived:boolean}>; reservations:Array<{id:string;name:string;currentStatus:string;opens:string}>; onSave:(doc:TravelDocument)=>void; mode?:"documents"|"readiness" }) {
 const [editing,setEditing]=useState<TravelDocument|null>(null); const [filter,setFilter]=useState("Todo");
 const summary=documentSummary(documents); const readiness=readinessItems(documents,hotels,reservations);
 if(mode==="readiness") { const items=filter==="Todo"?readiness:filter==="Listo"?[]:readiness.filter(i=>filter==="Pendiente"?i.status==="Pendiente":true); return <section className="documentsScreen"><div className="documentsHero"><div><span>Antes de viajar</span><h2>{readiness.length} cosas pendientes</h2><p>Este checklist lee documentos, hoteles y reservas existentes; no duplica información.</p></div></div><div className="filterStrip">{["Todo","Pendiente","Próximamente","Listo"].map(f=><button className={filter===f?"active":""} key={f} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="readinessList">{items.map(i=><article key={i.id}><span>{i.category}</span><h4>{i.title}</h4><p>{i.note}</p><strong>{i.status}</strong></article>)}</div></section> }
 return <section className="documentsScreen"><div className="documentsHero"><div><span>Documentos de viaje</span><h2>{summary.ready} listos · {summary.pending} pendientes</h2><p>eTA, Visit Japan Web, pasaportes y seguro en un solo lugar.</p></div><FileCheck2 size={32}/></div><div className="documentGrid">{documents.map(doc=><article key={doc.id} className={`documentCard doc-${doc.status.toLowerCase().replaceAll(" ","-")}`}><span>{doc.country} · {doc.type}</span><h3>{doc.title}</h3><strong>{doc.travelerLabel}</strong><p>{doc.notes}</p><div className="documentStatus">{["Aprobado","Completado"].includes(doc.status)?"✅":"⏳"} {doc.status}</div>{doc.passportLast4?<small>Pasaporte •••• {doc.passportLast4}</small>:null}<div className="actionRow">{doc.url?<a className="chipButton" href={doc.url} target="_blank" rel="noreferrer"><ExternalLink size={14}/>Abrir</a>:null}<button className="chipButton" type="button" onClick={()=>setEditing(doc)}><Pencil size={14}/>Ver detalles</button></div></article>)}</div>{editing?<DocumentEditor document={editing} onClose={()=>setEditing(null)} onSave={(d)=>{onSave(d);setEditing(null)}}/>:null}</section>
}
function DocumentEditor({document,onClose,onSave}:{document:TravelDocument;onClose:()=>void;onSave:(d:TravelDocument)=>void}){const[draft,setDraft]=useState(document);const update=<K extends keyof TravelDocument>(k:K,v:TravelDocument[K])=>setDraft(c=>({...c,[k]:v}));return <Modal open title={`${draft.title} · ${draft.travelerLabel}`} onClose={onClose} footer={<button className="primaryAction" type="button" onClick={()=>onSave({...draft,updatedAt:new Date().toISOString().slice(0,10)})}>Guardar</button>}><div className="formGrid"><label>Estado<select value={draft.status} onChange={e=>update("status",e.target.value as TravelDocument["status"])}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Últimos 4 del pasaporte<input maxLength={4} value={draft.passportLast4} onChange={e=>update("passportLast4",e.target.value.replace(/\D/g,"").slice(0,4))}/></label><label>Emisión<input type="date" value={draft.issuedAt} onChange={e=>update("issuedAt",e.target.value)}/></label><label>Vencimiento<input type="date" value={draft.expiresAt} onChange={e=>update("expiresAt",e.target.value)}/></label><label className="full">Referencia / número opcional<input value={draft.reference} onChange={e=>update("reference",e.target.value)}/></label><label className="full">URL / QR / comprobante<input value={draft.attachmentUrl || draft.url} onChange={e=>update("attachmentUrl",e.target.value)}/></label><label className="full">Notas<textarea rows={4} value={draft.notes} onChange={e=>update("notes",e.target.value)}/></label></div></Modal>}
