import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const requireVite = createRequire(import.meta.resolve('vite'));
const { build } = requireVite('esbuild');
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'japan-trip-test-'));
const bundle = path.join(dir, 'runtime.mjs');
await build({ stdin: { contents: 'export { captureActivityBlackBox } from "./src/utils/activityBlackBox"; export { loadInitialState } from "./src/hooks/useTripStore"; export { recoverProtectedTrip } from "./src/utils/protectedRecovery"; export { stateSelectionFingerprint } from "./src/utils/syncProtocol";', resolveDir: process.cwd() }, bundle: true, platform: 'node', format: 'esm', outfile: bundle });
const { loadInitialState, recoverProtectedTrip, stateSelectionFingerprint, captureActivityBlackBox } = await import(pathToFileURL(bundle));
const baseline = JSON.parse(fs.readFileSync('src/data/recoveryTrip.json', 'utf8'));
const key = 'japan-trip-2026-2027-state-v1';
const marker = 'japan-trip-2026-2027-recovery-baseline';
let values;
globalThis.localStorage = { getItem: k => values.get(k) ?? null, setItem: (k, v) => values.set(k, v) };
const counts = s => [s.activities.length, s.activities.filter(a => a.included).length, s.zonePlaces.length, s.zonePlaces.filter(p => p.selected).length];
values = new Map();
const fresh = loadInitialState();
assert.deepEqual(counts(fresh), [124,121,93,80], 'runtime migrations must preserve protected totals');
assert.equal(values.get(marker), undefined, 'initial render must not prematurely mark durable recovery');
const recent = structuredClone(fresh);
recent.activities[0].note = 'Latest user note';
recent.purchases.push({...recent.purchases[0],id:'test-new-purchase'});
recent.activityBlackBox = captureActivityBlackBox(recent);
recent.activityBlackBox.updatedAt = '2026-10-04T19:00:00.000Z';
values = new Map([[key,JSON.stringify(recent)]]);
let loaded = loadInitialState();
assert.equal(loaded.activities[0].note, recent.activities[0].note);
assert.ok(loaded.purchases.some(p=>p.id==='test-new-purchase'));
assert.equal(values.get(`${key}-before-recovery`),JSON.stringify(recent));
assert.equal(loaded.activityBlackBox.updatedAt,recent.activityBlackBox.updatedAt,'migration is not a new user decision');
const legacy = structuredClone(recent);
legacy.activities = legacy.activities.slice(0,61);
legacy.zonePlaces.forEach(p=>p.selected=false);
values = new Map([[key,JSON.stringify(legacy)]]);
loaded = loadInitialState();
assert.deepEqual(counts(loaded),[124,121,93,80]);
assert.ok(loaded.purchases.some(p=>p.id==='test-new-purchase'),'repair keeps later purchases');
const edited = structuredClone(fresh);
edited.activities.find(a=>a.included).included=false;
edited.zonePlaces.find(p=>p.selected).selected=false;
edited.activityBlackBox = undefined;
values = new Map([[key,JSON.stringify(edited)],[marker,'protected-124-2026-09-27']]);
loaded=loadInitialState();
assert.deepEqual(counts(loaded),[124,120,93,79],'completed recovery must respect subsequent user choices');
const repaired = recoverProtectedTrip(legacy,baseline,true);
assert.deepEqual(counts(repaired),[124,121,93,80]);
assert.equal(legacy.activities.length,61,'repair never mutates its source');
assert.equal(stateSelectionFingerprint(recoverProtectedTrip(repaired,baseline,true)),stateSelectionFingerprint(repaired),'repair is idempotent');
const custom=structuredClone(recent); custom.activities.push({...custom.activities[0],id:'custom-new',included:true});
assert.equal(recoverProtectedTrip(custom,baseline,true).activities.length,125,'custom records survive recovery');
console.log('Runtime recovery tests passed: 124/121/93/80, current notes/purchases/custom items, durable marker, legacy repair, idempotence, and later user decisions.');
fs.rmSync(dir,{recursive:true,force:true});

await import('./validateSync.mjs');
