import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import vm from 'node:vm';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const { build } = createRequire(import.meta.resolve('vite'))('esbuild');
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'japan-sync-test-'));
const outfile = path.join(dir,'sync.mjs');
const mock = `
export const memory=new Map(); export let commits=0;
export const doc=(_db,...parts)=>parts.join('/');
export const collection=doc;
export const serverTimestamp=()=> 'server-time';
const snapshot=(ref)=>({ref,id:ref.split('/').at(-1),exists:()=>memory.has(ref),data:()=>structuredClone(memory.get(ref))});
export const getDocFromServer=async ref=>snapshot(ref);
export const getDocsFromServer=async ref=>{const docs=[...memory.keys()].filter(k=>k.startsWith(ref+'/')&&!k.slice(ref.length+1).includes('/')).map(snapshot);return {docs,size:docs.length,forEach:fn=>docs.forEach(fn)}};
export const setDoc=async (ref,data)=>memory.set(ref,structuredClone(data));
export const deleteDoc=async ref=>memory.delete(ref);
export const onSnapshot=()=>()=>{};
export const runTransaction=async (_db,fn)=>{const staged=[];await fn({get:getDocFromServer,set:(ref,data,options)=>staged.push(()=>memory.set(ref,options?.merge?{...memory.get(ref),...data}:data)),delete:ref=>staged.push(()=>memory.delete(ref))});staged.forEach(fn=>fn());commits++};
`;
await build({stdin:{contents:'export { writeTripState, readTripStateFromServer, verifyTripStateFromServer } from "./src/services/tripRepository"; export { memory, commits } from "firebase/firestore";',resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',outfile,define:{'import.meta.env.VITE_TRIP_ID':'"japan-trip-2026-2027"'},plugins:[{name:'mock-firestore',setup(b){b.onResolve({filter:/^firebase\/firestore$/},()=>({path:'mock',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:mock,loader:'js'}))}}]});
const api=await import(pathToFileURL(outfile));
const state=JSON.parse(fs.readFileSync('src/data/recoveryTrip.json','utf8'));
const db={}; const receipt=await api.writeTripState(db,state,undefined,null);
assert.equal(api.commits,1,'one atomic commit for the whole trip');
const remote=await api.readTripStateFromServer(db,state);
assert.equal(remote.manifest.revision,receipt.revision);
assert.equal(remote.state.activities.filter(a=>a.included).length,121);
assert.equal(remote.state.zonePlaces.filter(p=>p.selected).length,80);
assert.ok(!('__revision' in remote.state.activities[0]));
const second = await api.writeTripState(db,state,undefined,receipt.revision);
assert.equal((await api.verifyTripStateFromServer(db,state,receipt.revision)).revision,second.revision,'identical concurrent save can be fully verified');
const mainPath='trips/japan-trip-2026-2027/settings/main';
const main=api.memory.get(mainPath); const originalNotes=main.notes;
main.notes='changed elsewhere';
await assert.rejects(api.verifyTripStateFromServer(db,state,receipt.revision),/Otra sesión/,'same selections cannot hide changed notes');
main.notes=originalNotes;
remote.manifest=(await api.readTripStateFromServer(db,state)).manifest;
const before=JSON.stringify([...api.memory]);
await assert.rejects(api.writeTripState(db,state,undefined,'stale-revision'),/otro dispositivo/);
assert.equal(JSON.stringify([...api.memory]),before,'conflicting writer leaves all cloud records untouched');
const manifestPath='trips/japan-trip-2026-2027/settings/sync-manifest';
api.memory.delete(manifestPath);
const legacy=await api.readTripStateFromServer(db,state);
assert.equal(legacy.manifest,null,'legacy cloud without manifest can be read before recovery');
assert.equal(legacy.state.activities.length,124);
api.memory.set(manifestPath,remote.manifest);
api.memory.delete('trips/japan-trip-2026-2027/activities/'+state.activities[0].id);
await assert.rejects(api.readTripStateFromServer(db,state),/incompleta/,'partial remote revision cannot be accepted');
console.log('Sync tests passed: atomic commit, verified selections, legacy/null manifest, concurrent-write rejection and incomplete cloud protection.');
// Exercise the actual service worker, including install and cache ownership.
const listeners=new Map(),deleted=[],cached=new Map();
const root='https://example.test/japan-trip-2026-2027/';
const cache={addAll:async urls=>urls.forEach(u=>cached.set(u,new Response(u===root?'<script src="assets/app.js"></script><link href="assets/app.css">':'asset'))),match:async r=>cached.get(typeof r==='string'?r:r.url)?.clone(),put:async(r,v)=>cached.set(typeof r==='string'?r:r.url,v)};
const context={URL,Response,console,self:{location:{href:root+'sw.js',origin:'https://example.test'},clients:{claim:async()=>{}},skipWaiting:async()=>{},addEventListener:(k,v)=>listeners.set(k,v)},caches:{open:async()=>cache,keys:async()=>['other-app-cache','japan-trip-2026-2027-v2','japan-trip-2026-2027-__BUILD_VERSION__'],delete:async key=>deleted.push(key)},fetch:async()=>{throw new Error('offline')}};
vm.runInNewContext(fs.readFileSync('public/sw.js','utf8'),context);
let pending; listeners.get('install')({waitUntil:p=>pending=p}); await pending;
assert.ok(cached.has(root+'assets/app.js')); assert.ok(cached.has(root+'assets/app.css'));
listeners.get('activate')({waitUntil:p=>pending=p});await pending;
assert.deepEqual(deleted,['japan-trip-2026-2027-v2'],'never delete another app cache');
let response;listeners.get('fetch')({request:{url:root,method:'GET',mode:'navigate'},respondWith:p=>response=p});assert.ok((await response).ok,'offline shell works');
response=undefined;listeners.get('fetch')({request:{url:'https://firestore.googleapis.com/test',method:'GET'},respondWith:p=>response=p});assert.equal(response,undefined,'Firebase requests bypass shell cache');
console.log('Service worker tests passed: offline JS/CSS shell, scoped cache cleanup and Firebase bypass.');
fs.rmSync(dir,{recursive:true,force:true});
