import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const {build}=createRequire(import.meta.resolve('vite'))('esbuild');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'japan-go-test-'));
const outfile=path.join(dir,'go.mjs');
await build({entryPoints:['src/utils/onTheGo.ts'],bundle:true,platform:'node',format:'esm',outfile});
const {japanClock,travelDay,travelFocus,directionsUrl,activityDestination}=await import(pathToFileURL(outfile));
const state=JSON.parse(fs.readFileSync('src/data/recoveryTrip.json','utf8'));
assert.deepEqual(japanClock(new Date('2026-12-25T15:05:00Z')),{date:'2026-12-26',time:'00:05',minutes:5});
assert.equal(japanClock(new Date('2026-12-25T03:00:00Z')).time,'12:00','Japan time must not depend on iPhone timezone');
assert.equal(travelDay(state.days,new Date('2026-10-04T12:00:00Z')).date,'2026-12-25','before trip preview starts in Japan');
assert.equal(travelDay(state.days,new Date('2026-12-25T15:05:00Z')).date,'2026-12-26','day rolls at Japanese midnight');
const day=state.days.find(d=>d.date==='2026-12-26');
const source=state.activities.find(a=>a.included);
const make=(id,order,start,end,status='idea',included=true)=>({...structuredClone(source),id,order,start,end,status,included,dayId:day.id});
const acts=[make('first',0,'09:00','10:00'),make('current',1,'11:00','12:00'),make('next',2,'13:00','14:00'),make('excluded',3,'11:30','12:30','idea',false)];
const now=new Date('2026-12-26T02:30:00Z');
assert.equal(travelFocus(acts,day,now,'clock').id,'current');
assert.equal(travelFocus(acts,day,now,'activities').id,'first','manual order preserved');
assert.equal(travelFocus(acts,day,now,'clock','next').id,'next','explicit user choice wins');
assert.equal(travelFocus(acts,day,now,'activities','',['first']).id,'current','skipping does not deselect an activity');
assert.equal(travelFocus(acts.map(a=>({...a,status:'completada'})),day,now,'clock'),null);
assert.equal(travelFocus(acts,day,new Date('2026-10-04T03:00:00Z'),'clock').id,'first','preview must not skip by current time');
const flightDay={...day,city:'Tokyo → Vancouver → Montréal'};
assert.equal(travelFocus(acts,flightDay,now,'clock').id,'first','international flight times cannot be treated as all JST');
const url=new URL(directionsUrl('Daruma Jeans & atelier, Tokyo','transit'));
assert.equal(url.searchParams.get('destination'),'Daruma Jeans & atelier, Tokyo');
assert.equal(url.searchParams.has('origin'),false,'Maps can use device location without app storing GPS');
assert.equal(url.searchParams.get('travelmode'),'transit');
assert.equal(url.searchParams.get('dir_action'),'navigate');
assert.equal(new URL(directionsUrl('Temple','walking','Hotel')).searchParams.get('origin'),'Hotel');
const transport={...source,category:'transport',place:'Hotel → Universal City Station',address:'Old hotel → station',lat:0,lon:0};
assert.ok(activityDestination(transport,'Osaka').startsWith('Universal City Station'),'navigate to destination rather than transport origin or stale coordinate');
assert.equal(activityDestination({...source,title:'Regreso al hotel'},'Osaka',{...state.hotels[0],address:'Correct hotel address'}),'Correct hotel address');
assert.equal(activityDestination({...source,category:'experience',kind:'experience',displayMode:'timed',place:'Narita International Airport (NRT)',address:'Narita International Airport (NRT)'},'Osaka'),'Narita International Airport (NRT), Japan','overnight city must not relocate arrival airport');
const before=JSON.stringify(acts);travelFocus(acts,day,now,'clock');assert.equal(JSON.stringify(acts),before,'travel view must never mutate selections/order');
console.log('On-the-go tests passed: Japan timezone/day rollover, itinerary order, clock focus, manual choice, skipping/completion, preview/flight safety and Maps links.');
fs.rmSync(dir,{recursive:true,force:true});

